(function(g){var window=this;'use strict';var qXa=function(a,b){var c=[];return g.ht(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},q4=function(a,b){return"getAll"in IDBIndex.prototype?g.Ws(a.j.getAll(b,void 0)):qXa(a,b)},rXa=function(a,b){return g.bt(a,["captions"],{mode:"readonly",
Lc:!0},function(c){return g.Xma(c.objectStore("captions"),b)})},sXa=function(a){var b=new g.Hx("und",new g.hA("Default","und",!0));
b.captionTracks=a.captionTracks;return b},tXa=function(a){return new g.wi(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.Eba(m,g.Ra(f,l),k);
else b(e)})},r4=function(a){this.j=a},s4=function(){r4.apply(this,arguments)},t4=function(){s4.apply(this,arguments)},u4=function(){s4.apply(this,arguments)},v4=function(){s4.apply(this,arguments)},w4=function(){r4.apply(this,arguments)},x4=function(){s4.apply(this,arguments)},y4=function(){s4.apply(this,arguments)},z4=function(){s4.apply(this,arguments)},A4=function(){s4.apply(this,arguments)},B4=function(){s4.apply(this,arguments)},C4=function(){s4.apply(this,arguments)},D4=function(){s4.apply(this,
arguments)},E4=function(){s4.apply(this,arguments)},F4=function(){s4.apply(this,arguments)},G4=function(){s4.apply(this,arguments)},H4=function(){s4.apply(this,arguments)},I4=function(){r4.apply(this,arguments)},J4=function(){s4.apply(this,arguments)},K4=function(){s4.apply(this,arguments)},L4=function(){s4.apply(this,arguments)},M4=function(){s4.apply(this,arguments)},N4=function(){s4.apply(this,arguments)},O4=function(){s4.apply(this,arguments)},P4=function(){s4.apply(this,arguments)},Q4=function(){s4.apply(this,
arguments)},R4=function(){s4.apply(this,arguments)},S4=function(){s4.apply(this,arguments)},T4=function(){s4.apply(this,arguments)},U4=function(){s4.apply(this,arguments)},V4=function(){s4.apply(this,arguments)},W4=function(){s4.apply(this,arguments)},X4=function(){s4.apply(this,arguments)},uXa=function(a){var b=g.wD();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Vua(b);JSON.stringify(b);return b},vXa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.tt(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.zD(b),3):d.return();c=d.u;return d.return(g.bt(c,["index","media","captions"],{mode:"readwrite",Lc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Us.all(e).then(function(){})}))})},wXa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.tt(),2);if(3!=c.j){a=c.u;if(!a)throw g.Ss("rvdfd");return g.A(c,g.zD(a),3)}b=c.u;return c.return(g.bt(b,["index","media"],{mode:"readwrite",Lc:!0},function(d){var e={};return g.ft(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Us.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.$ua(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Us.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},k=g.r(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=uXa(f);return g.$ma(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.dva);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},xXa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.tt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Ss("wct");return g.A(e,g.zD(c),3)}d=e.u;return g.A(e,g.bt(d,["captions"],{mode:"readwrite",Lc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.ct(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Us.all(k)}),0)})},yXa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.tt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Ss("gactfv");return g.A(e,g.zD(c),3)}d=e.u;return e.return(rXa(d,b))})},zXa=function(a){return g.B(function(b){g.yD(a,0);
return b.return(vXa(a))})},AXa=function(a){return{context:g.uG(),
videoIds:a}},Y4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},Z4=function(a,b){b=void 0===b?{}:b;
g.Is.call(this,g.nTa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Z4.prototype)},BXa=function(a){return new Z4("WRONG_DATA_TYPE",{zV:a})},CXa=function(a){return a instanceof Error?new Z4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Z4("UNKNOWN_ENCODE_ERROR")},DXa=function(a){return a instanceof Error?new Z4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Z4("UNKNOWN_DECODE_ERROR")},EXa=function(a,b){a=a instanceof
Z4?a:b(a);
g.Iv(a);throw a;},FXa=function(){},GXa=function(a,b,c){try{return a.B(b,c)}catch(d){EXa(d,CXa)}},HXa=function(a,b,c){try{return a.u(b,c)}catch(d){EXa(d,DXa)}},$4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},a5=function(a){this.j=a},b5=function(){},IXa=function(){this.j={};
this.j[0]=new b5;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Js();var c=$4(b);var d=new a5(new g.NB(c),new g.MB(c))}catch(e){throw a=e instanceof Error?new Z4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Z4("KEY_CREATION_FAILED"),g.Iv(a),a;}a[1]=d}},c5=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Z4("INVALID_ENCODER_VERSION",{zV:b}),g.Iv(b),b;return a},KXa=function(a){var b=JXa[a];
if(b)return b;g.Jv(new g.Is("Entity model not found.",{entityType:a}))},LXa=function(a){var b=new IXa,c=a.objectStore("EntityStore"),d=a.objectStore("EntityAssociationStore");
g.ft(c,{},function(e){var f=e.getValue(),k=HXa(c5(b,f.version),f.data,f.key),l=g.kJ(f.key).entityType;l=KXa(l);if(!l)return e.continue();l=(new l(k)).kd();k=[];l=g.r(l);for(var m=l.next();!m.done;m=l.next())k.push(g.ct(d,{parentEntityKey:f.key,childEntityKey:m.value}));return g.Us.all(k).then(function(){return e.continue()})})},MXa=function(){if(d5)return d5();
var a={};d5=g.Ht("PersistentEntityStoreDb",{Yr:(a.EntityStore={No:1},a.EntityAssociationStore={No:2},a),Az:!1,upgrade:function(b,c,d){c(1)&&g.et(g.$s(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.$s(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.et(b,"byParentEntityKey","parentEntityKey"),g.et(b,"byChildEntityKey","childEntityKey"));c(3)&&!c(1)&&LXa(d)},
version:g.Q("pes_migrate_association_data")?3:2});return d5()},NXa=function(a){return g.lt(MXa(),a)},OXa=function(a,b){this.j=a;
this.u=b;this.B={}},PXa=function(a,b){return HXa(c5(a.u,b.version),b.data,b.key)},e5=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return PXa(a,d)}})},f5=function(a,b,c){return c?(c=c.map(function(d){return e5(a,d,b)}),g.Us.all(c)):q4(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return PXa(a,e)})})},h5=function(a,b,c){var d=Y4(b),e=c5(a.u,1),f={key:d,
entityType:c,data:GXa(e,b,d),version:1};return a.j.objectStore("EntityStore").get(d).then(function(k){if(k&&k.entityType!==c)throw Error("Incorrect entity type");}).then(function(){return g.Us.all([g.ct(a.j.objectStore("EntityStore"),f),
QXa(a,b,c)])}).then(function(){g5(a,d,c);
return d})},i5=function(a,b,c){b=b.map(function(d){return h5(a,d,c)});
return g.Us.all(b)},j5=function(a,b,c){if(null==c?0:c.rF){var d=new Set;
return RXa(a,b,d).then(function(){for(var f=[],k=g.r(d),l=k.next();!l.done;l=k.next())f.push(j5(a,l.value));return g.Us.all(f).then(function(){})})}var e=g.kJ(b).entityType;
return g.Us.all([a.j.objectStore("EntityStore").delete(b),k5(a,b)]).then(function(){g5(a,b,e)})},SXa=function(a,b){return g.ht(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Us.all([c.delete(),
k5(a,c.zB())]).then(function(){g5(a,c.zB(),b);return c.continue()})})},TXa=function(a,b,c,d){var e=c5(a.u,1);
return e5(a,b,d).then(function(f){if(f){f=g.VI(f,c);var k={key:b,entityType:d,data:GXa(e,f,b),version:1};return g.Us.all([g.ct(a.j.objectStore("EntityStore"),k),QXa(a,f,d)])}}).then(function(){g5(a,b,d);
return b})},g5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},UXa=function(a,b,c){var d=Y4(b);
c=KXa(c);if(!c)return g.Us.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.kd());for(var e=c.next();!e.done;e=c.next())b.push(g.ct(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Us.all(b).then(function(f){return f.map(function(k){return k[1]})})},k5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},QXa=function(a,b,c){var d=Y4(b);
return k5(a,d).then(function(){return UXa(a,b,c)})},RXa=function(a,b,c){if(c.has(b))return g.Us.resolve(void 0);
c.add(b);return VXa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Us.resolve(void 0),f={};
d=g.r(d);for(var k=d.next();!k.done;f={LD:f.LD},k=d.next())f.LD=k.value,e=e.then(function(l){return function(){return RXa(a,l.LD,c)}}(f));
return e}).then(function(){})},VXa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return q4(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(q4(c.index("byChildEntityKey"),f.childEntityKey));return g.Us.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},l5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Js());a.onmessage=this.B.bind(this);this.channel=a},m5=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,NXa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.bt(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new OXa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),WXa(a,k)));return l.return(f)})},n5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},o5=function(a,b,c){return m5(a,{mode:"readwrite",
Lc:!0},function(d){return h5(d,b,c)})},XXa=function(a,b){return m5(a,{mode:"readwrite",
Lc:!0},function(c){return i5(c,b,"offlineOrchestrationActionWrapperEntity")})},YXa=function(a,b){return m5(a,{mode:"readwrite",
Lc:!0},function(c){return j5(c,b)})},p5=function(a,b,c){return m5(a,{mode:"readonly",
Lc:!0},function(d){return e5(d,b,c)})},q5=function(a,b,c){return m5(a,{mode:"readonly",
Lc:!0},function(d){return f5(d,b,c)})},WXa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},ZXa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.ta(d,2),g.A(d,g.tt(),4);if(2!=d.j){a=d.u;if(!a||!g.Ks()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new IXa;return d.return(new l5(a,b))}c=g.va(d);c instanceof Error&&g.Iv(c);return d.return()})},s5=function(){r5||(r5=ZXa());
return r5},$Xa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},aYa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,s5(),2):(b=c.u)?g.A(c,m5(b,"readwrite",function(d){for(var e={},f={},k=g.r(a),l=k.next();!l.done;f={ih:f.ih,qt:f.qt},l=k.next())f.ih=l.value,f.ih.entityKey&&$Xa(f.ih)&&(f.qt=g.Gf(f.ih.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.ih.type&&(l=function(m){return function(){return h5(d,m.ih.payload[m.qt],m.qt)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.ih.type&&(l=function(m){return function(){return j5(d,m.ih.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.ih.type&&(l=function(m){return function(){return TXa(d,m.ih.entityKey,m.ih.payload[m.qt],m.qt)}}(f)),l&&(e[f.ih.entityKey]=e[f.ih.entityKey]?e[f.ih.entityKey].then(l):l()));
return g.Us.all(Object.values(e))}),0):c.return()})},bYa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.A0){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.A0.dispatch(d)}return g.A(c,aYa(b),2)}b.length=0;g.sa(c)})},cYa=function(a){return void 0!==a},t5=function(a,b,c){g.Jv(new g.Is("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Jv(b)},dYa=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y,z,E;
return g.B(function(J){if(1==J.j)return g.A(J,m5(a,{mode:"readonly",Lc:!0},function(I){return f5(I,"playbackData").then(function(N){var Z=N.map(function(ra){return ra.transfer}).filter(function(ra){return!!ra}),K=N.map(function(ra){return ra.offlineVideoPolicy}).filter(function(ra){return!!ra});
Z=f5(I,"transfer",Z);K=f5(I,"offlineVideoPolicy",K);return g.Us.all([Z,K]).then(function(ra){var za=g.r(ra);ra=za.next().value;za=za.next().value;return[N,ra,za]})})}),2);
b=J.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(v=t.value)&&(n[v.key]=v);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=k.map(function(I){var N=n[I.transfer],Z=p[I.offlineVideoPolicy];I=g.kJ(Z.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===Z.action){var K="OFFLINE_VIDEO_STATE_DISABLED";Z.expirationTimestamp&&Number(Z.expirationTimestamp)<Date.now()/1E3&&(K="OFFLINE_VIDEO_STATE_EXPIRED");
Z=K}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===Z.action)Z="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==N?void 0:N.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":K="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":K="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":K="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":K="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":K="OFFLINE_VIDEO_STATE_PLAYABLE";
break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":K="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:K="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===K)switch(null==N?void 0:N.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":K="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":K="OFFLINE_VIDEO_STATE_STREAMS_MISSING";break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":K=
"OFFLINE_VIDEO_STATE_NETWORK_ERROR"}Z=K}I={id:I,videoState:Z};if(null==N?0:N.cotn)I.cotn=N.cotn;if(null==N?0:N.maximumDownloadQuality)I.selectedVideoQuality=null==N?void 0:N.maximumDownloadQuality;return I});
return J.return({offlineVideos:E})})},eYa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,dYa(a),2);b=c.u;g.Ds("offlineStateSnapshot",b);g.sa(c)})},u5=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Js()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Js()),this.u.onmessage=this.C.bind(this))},v5=function(a,b){a.api.Oa("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},fYa=function(){this.locks=navigator.locks},gYa=function(){try{var a=g.Ia("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new fYa,g.Ha("ytglobal.locks_",a),a}catch(d){}},iYa=function(a,b,c,d){var e=this;
this.S=a;this.Y=b;this.visibility=c;this.N=d;this.C=this.J=this.D=this.u=this.j=!1;this.K=new g.L(function(){hYa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.uf()})},jYa=function(a){if(!a.u&&!a.j){var b=gYa();
if(b){a.u=!0;var c=g.Js("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.ta(l,2),a.B=new g.Qj,a.j=!0,a.u=!1,g.A(l,a.S(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.ua(l,0);break;case 2:d=g.va(l),(null==(f=(e=a).N)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||hYa(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",CC:d.name}],g.Iv(k)),g.sa(l)}})})}}},kYa=function(a){a.j&&(a.C=
!0,w5(a))},lYa=function(a,b){a.j&&(a.D=b,w5(a))},mYa=function(a,b){a.j&&(a.J=b,w5(a))},w5=function(a){a.J&&a.D&&a.C&&a.visibility.isBackground()?g.yp(a.K,6E4):a.K.stop()},hYa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.Y()},x5=function(a,b){var c=b.gj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.Ds("offlineTransferStatusChanged",a)},nYa=function(a){x5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},oYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
y5=function(){},z5=function(){},A5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Js("CacheStorage get")},pYa=function(){return g.B(function(a){if(void 0!==B5)return a.return(B5);
B5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.ta(d,2),g.A(d,C5.open("test-only"),4);case 4:return g.A(d,C5.delete("test-only"),5);case 5:g.ua(d,3);break;case 2:if(c=g.va(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.sa(d)}})});
return a.return(B5)})},E5=function(){return g.B(function(a){if(1==a.j)return g.A(a,pYa(),2);
if(!a.u)return a.return(void 0);D5||(D5=new z5);return a.return(D5)})},qYa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,E5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},rYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,E5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},sYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,E5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},F5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},G5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},H5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},J5=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,v,x,y,z,E,J,I,N,Z,K,ra,za,Pa,Sa,ac,zb;
return g.B(function(yc){switch(yc.j){case 1:return e=g.lJ(a,"ytMainVideoEntity"),f=g.lJ(a,"ytMainChannelEntity"),k=g.lJ(a,"transfer"),g.A(yc,m5(b,{mode:"readonly",Lc:!0},function(Rc){return g.Us.all([e5(Rc,e,"ytMainVideoEntity"),e5(Rc,f,"ytMainChannelEntity"),e5(Rc,k,"transfer"),f5(Rc,"ytMainChannelEntity"),f5(Rc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=yc.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;v=m.next().value;x=n;y=p;z=q;E=t;J=v;if(!x&&!y){yc.Va(3);break}I=x?I5(x.thumbnail):[];if(!y){N=[];yc.Va(4);break}return g.A(yc,tYa(y,E),5);case 5:N=yc.u;case 4:return Z=N,g.A(yc,rYa(I.concat(Z)),3);case 3:K=[];ra=g.lJ(a,"ytMainDownloadedVideoEntity");za=g.lJ(a,"mainVideoEntity");Pa=g.r(J);for(Sa=Pa.next();!Sa.done;Sa=Pa.next())ac=Sa.value,zb=g.kJ(ac.key).entityId,zb!==a||uYa(c,ac.actionProto)||K.push(ac.key);
return g.A(yc,m5(b,{mode:"readwrite",Lc:!0},function(Rc){var gd=K.map(function(he){return j5(Rc,he)});
gd.push(j5(Rc,ra,{rF:!0}));gd.push(j5(Rc,za,{rF:!0}));return g.Us.all(gd)}),7);
case 7:vYa(z),v5(d,{entityKey:ra,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.sa(yc)}})},xYa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,m5(a,{mode:"readwrite",Lc:!0},function(p){var q=f5(p,"transfer"),t=f5(p,"offlineOrchestrationActionWrapperEntity");return g.Us.all([q,t]).then(function(v){v=g.r(v);var x=v.next().value,y=v.next().value;v=wYa.map(function(I){return SXa(p,I)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.kJ(z.actionProto.entityKey).entityType,J="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;uYa(b,z.actionProto)||E&&(!E||J)||v.push(j5(p,z.key,{rF:!0}))}return g.Us.all(v).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,vYa(k),l=g.kJ(k.key).entityId,m=g.lJ(l,"ytMainDownloadedVideoEntity"),v5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,qYa(),0)})},uYa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},vYa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.kJ(a.key).entityId;
x5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,gj:a})}},I5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},tYa=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=I5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(I5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},K5=function(a){this.j=a},yYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Va(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.B(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Va(2);break;case 4:return n.return(c)}})},L5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},M5=function(a,b,c){this.j=a;
this.X=b;this.u=c},BYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.ta(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,zYa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,SR:q}),4);case 4:return(k=n.u)?g.A(n,AYa(a,k,b),5):n.return(N5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(N5(b,!0,k.orchestrationActions));case 2:return l=g.va(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Ns&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),t5("PDE handleAdd error"),n.return(N5(b,!1,void 0,m))}})},CYa=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v,x,y,z;
return g.B(function(E){switch(E.j){case 1:return c=b.entityKey,g.A(E,m5(a.j,{mode:"readonly",Lc:!0},function(J){var I=e5(J,c,"playbackData"),N=e5(J,g.lJ(g.kJ(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");J=e5(J,g.lJ(g.kJ(b.entityKey).entityId,"transfer"),"transfer");return g.Us.all([I,N,J])}),2);
case 2:d=E.u;e=g.r(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return E.return(N5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(v=p)?0:v.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.ta(E,3);return g.A(E,zYa(a,c,{refreshData:q,SR:t}),5);case 5:return(x=E.u)?g.A(E,AYa(a,x,b),6):E.return(N5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return E.return(N5(b,
!0,x.orchestrationActions));case 3:return y=g.va(E),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.Ns&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),E.return(N5(b,!1,void 0,z))}})},zYa=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.GI();var l=a.X,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.SR,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.SI(l),signatureTimestamp:19096,videos:[q]};f=g.pI(DYa);return k.return(g.AG(d,e,f))})},AYa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Va(2);d=g.kJ(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,J5(d,a.j,c,a.u),2)}return g.A(e,bYa(b.frameworkUpdates.entityBatchUpdate),0)})},N5=function(a,
b,c,d){return new L5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",F5(a),c,d)},O5=function(){K5.apply(this,arguments)},FYa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.A(e,p5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(e,3);return g.A(e,EYa(a,b),5);case 5:g.ua(e,4);break;case 3:return g.va(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},GYa=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.A(e,p5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(e,3);return g.A(e,EYa(a,b,!0),5);case 5:g.ua(e,4);break;case 3:return g.va(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},EYa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Pv(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c},m=g.kJ(l.key).entityId,g.A(n,m5(a.j,{mode:"readwrite",Lc:!0},function(p){var q=[];c&&q.push(j5(p,
g.lJ(m,"offlineVideoStreams")));q.push(h5(p,l,"transfer"));return g.Us.all(q)}),2);
x5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,gj:l});g.sa(n)})},HYa=function(a,b,c){return new g.TD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},IYa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},P5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},Q5=function(a){return{key:g.lJ(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},JYa=function(){this.j=new Map},KYa=function(){R5||(R5=new JYa);
return R5},LYa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},MYa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Pv(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.Ds("flowEvent",a,void 0)},NYa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.kJ(a.action.entityKey);a={entityType:d.CV,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},S5=function(a,b){var c={offlineOrchestrationContext:NYa(a)};
b=LYa(b,c);MYa(KYa(),b,a.rootActionId)},T5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:NYa(a,b,c)};b=LYa(3,b);MYa(KYa(),b,a.rootActionId)},OYa=function(){this.actions=[]},PYa=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,S5(c,1),a.actions.push(c);a.actions.sort(a.j)},QYa=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},U5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.ma=b;this.Y=c;this.D=d;this.j=new OYa;this.S=new g.Ut;this.C=new g.L(function(){e.retry()});
this.J=NaN;g.H(this,this.C);this.K=n5(this.u,this.Z.bind(this))},SYa=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new U5(a,b,c,d),g.A(f,RYa(e),2);e.B?Promise.resolve():V5(e);return f.return(e)})},V5=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();lYa(a.Y,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.ma[b.entityType]){z.Va(2);break}a.B=void 0;return g.A(z,V5(a),3);case 3:return z.return();case 2:f=g.r(c);for(k=f.next();!k.done;k=f.next())l=k.value,S5(l,2);g.ta(z,
4,5);return g.A(z,yYa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.r(c),k=n.next();case 8:if(k.done){z.Va(5);break}p=k.value;q=m.get(p.action);return g.A(z,TYa(a,p,q),9);case 9:k=n.next();z.Va(8);break;case 5:g.wa(z);a.B=void 0;g.xa(z,6);break;case 4:return t=g.va(z),t5("Orchestration error",t),g.ta(z,12),g.A(z,UYa(a,c),14);case 14:g.ua(z,5);break;case 12:v=g.va(z);t5("Orchestration retry error",v);x=g.r(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&PYa(a.j,[y]);z.Va(5);break;case 6:return g.A(z,V5(a),0)}})},TYa=function(a,
b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return T5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},v5(a.D,m),t5("Orchestration subactions creation error",p),n.return()}T5(b,c,k);return g.A(n,m5(a.u,{mode:"readwrite",Lc:!0},function(p){var q=[];if(k){var t=k.map(function(v){return Q5(v)});
q.push(i5(p,t,"offlineOrchestrationActionWrapperEntity"))}t=Q5(b);q.push(j5(p,t.key));return g.Us.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Va(0);
T5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,UYa(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};v5(a.D,f);t5("Orchestration result is not retryable, deleting action");return g.A(n,YXa(a.u,Q5(b).key),0)}S5(b,4);g.sa(n)})},W5=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=VYa(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.J)&&(a.J=d,a.C.start(e));a.S.tf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!WYa.includes(y)}),v=c.length<t,!a.C.isActive()&&v&&a.C.start(1));
0<c.length&&XYa(a,c);return g.A(x,a.B?Promise.resolve():V5(a),0)})},ZYa=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,YYa(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.kJ(f.key),l=k.entityId,QYa(a.j,l)||c.push(f);return g.A(m,W5(a,c),0)})},VYa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},UYa=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,$Ya(a,b),0)})},RYa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,q5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,W5(a,b),0)})},XYa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.kJ(c.key),e=g.kJ(c.actionProto.entityKey);c=new P5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&PYa(a.j,[c])})},YYa=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(cYa))})},$Ya=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return Q5(c)});
return XXa(a.u,b)},aZa=function(){this.j=void 0},cZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.V();e=!0;if(b.captionTracks.length)f=sXa(b),a.j=new g.gK(d,b,f);else if(b.Kc)k=g.pwa(b),a.j=new g.iK(d,b.Kc,c,k,b.jk),e=b.jk;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Vu(function(){return g.B(function(p){if(1==p.j)return g.A(p,bZa(a,c,e),2);m();g.sa(p)})})}))})},bZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,q,t,v,x,y,z;return g.B(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.dK(a.j.u,c);f=[];k={};l=g.r(e.entries());for(m=l.next();!m.done;k={HD:k.HD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,k.HD=q,v=t,x=a.j.Ar(v,"json3"),y=g.Jr(x,{withCredentials:!0,format:"RAW"},3,500).then(function(J){return function(I){I={metadata:g.ED(e[J.HD]),trackData:I.xhr.responseText};f.push(I)}}(k)).Ei(function(J){t5("Caption fetch error",J)}),d.push(y);
return g.A(E,tXa(d),2);case 2:return g.ta(E,3),g.A(E,xXa(b,f),5);case 5:g.ua(E,0);break;case 3:z=g.va(E),t5("Caption DB transaction error",z),g.sa(E)}})},dZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,yXa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},eZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.iP("woffle");this.u=!1},fZa=function(a){return g.B(function(b){return b.return(zXa(a))})},gZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.ava(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},X5=function(a,b){var c=g.xD(b);
if(1===c||0===c)return Promise.resolve();(c=hZa(a,b))&&c.stopVideo();a.B=0;return fZa(b)},Y5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.xD(e)&&((b=hZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.yD(e,2),a.B=2,c?iZa(a.j):d&&jZa(a.j))},hZa=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},kZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},Z5=function(a){g.G.call(this);
this.j=a;this.u=n5(this.j,this.B.bind(this))},lZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.lJ(p,"transfer")});
return g.A(n,q5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(cYa).map(function(p){return g.kJ(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.r(f);l=k.next();case 3:if(l.done){n.Va(5);break}m=l.value;return g.A(n,fZa(m),4);case 4:l=k.next();n.Va(3);break;case 5:return n.return(f)}})},nZa=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",t5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.lJ(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Yb()):void 0};return g.A(n,m5(a,{mode:"readwrite",Lc:!0},
function(p){var q=e5(p,l,"offlineVideoStreams"),t=e5(p,g.lJ(b,"transfer"),"transfer");return g.Us.all([q,t]).then(function(v){var x=g.r(v);v=x.next().value;x=x.next().value;if(!x)return j5(p,l).then(function(){});
v=[h5(p,mZa(v,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),v.push(h5(p,x,"transfer")));return g.Us.all(v)})}),0)})},oZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.lJ(b,"offlineVideoStreams"),g.A(l,p5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,o5(a,d,"offlineVideoStreams"),0)})},mZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},$5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.Aa=c;this.va=d;this.D=new g.Ut;this.C=new g.L(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.tf()&&(3>(e.j.transferRetryCount||0)?Y5(e.J,e.B,!1,!1):X5(e.J,e.B.videoDetails.videoId),e.hs("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.Y=0;this.ra=new g.iA(this);this.K=n5(this.u,this.jU.bind(this));this.J=new eZa(b,this);this.Ia=new aZa;this.S=new Z5(this.u);this.ma=this.D.Ma("publicytnetworkstatus-online",this.rz.bind(this));this.Z=this.D.Ma("publicytnetworkstatus-offline",this.w_.bind(this));g.H(this,this.ra);this.ra.T(b,"offlinetransferpause",this.x_);this.Ga=g.sB(this.api.V().experiments,"web_player_transfer_timeout_threshold_ms")},pZa=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,wXa(),2);
else{var c=a.S;var d=g.wD();d=Object.keys(d);c=lZa(c,d);b=g.A(b,c,0)}return b})},b6=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,qZa(a),2)}return 4!=d.j?(c=d.u,mYa(a.Aa,!c),c&&a.D.tf()?b?g.A(d,new Promise(function(e){g.Br(e,1E3)}),4):d.Va(4):(!c&&a.j&&a6(a),d.Va(0))):g.A(d,rZa(a,c),0)})},sZa=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,X5(a.J,a.B.videoDetails.videoId),3):b.Va(0);
a6(a);g.sa(b)})},tZa=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.ta(f,2),(c=!!b.captionTracks.length||!!b.Kc)?g.A(f,dZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,cZa(a.Ia,b),5);case 5:g.ua(f,0);break;case 2:e=g.va(f),t5("Caption downloading error",e,b.cotn),g.sa(f)}})},rZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.kJ(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState?x5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,gj:a.j}):"TRANSFER_STATE_TRANSFER_IN_QUEUE"!==a.j.transferState||a.j.transferRetryCount||2===g.xD(c.entityId)||x5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!0},{videoId:c.entityId,gj:a.j}),g.A(l,c6(a),
2);case 2:return d=null,g.ta(l,3),g.A(l,uZa(a,b),5);case 5:d=l.u;a.B=d;g.ua(l,4);break;case 3:return e=g.va(l),t5("error getting player response",e,b.cotn),g.A(l,a.hs("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=HYa(a.api.V(),b.cotn,d),g.A(l,tZa(a,f),7);case 7:return k=f,g.A(l,gZa(f.videoId),8);case 8:k.Rm=l.u;var m=a.J,n=b.maximumDownloadQuality;f.getPlayerResponse();g.yD(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Uo(9,f);p={};
g.jv(m.player,(p.localmediachange=m.uC,p.signatureexpired=m.WH,p.statechange=m.nY,p),m);n=kZa(n);m.N("hoffle_lmqf_killswitch")||g.ALa(m.player,g.Kx(n,n,!0,"m"),!1);g.yO(m.player,!1);d6(a);g.sa(l)}})},qZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(a.u,"transfer"),2);b=d.u;c=b.filter(vZa).sort(wZa);return 0===c.length?d.return():d.return(c[0])})},c6=function(a){return g.B(function(b){d6(a);
return g.A(b,e6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},iZa=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,e6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.kJ(a.j.key);nYa({videoId:b.entityId,gj:a.j});a6(a);b6(a);g.sa(c)})},jZa=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,e6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
a6(a);g.sa(b)})},xZa=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Va(2);break}b=HYa(a.api.V(),a.j.cotn,a.B);return g.A(e,tZa(a,b),2);case 2:return g.A(e,e6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.kJ(a.j.key),d=c.entityId,g.A(e,oZa(a.u,d),5);case 5:x5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,gj:a.j}),a6(a),b6(a),g.sa(e)}})},yZa=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Va(2);break}return g.A(e,c6(a),2);case 2:d=Date.now();if(!(1E3<d-a.Y)){e.Va(4);break}a.Y=d;return g.A(e,nZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:var f=Math.floor(c.bytesDownloaded/1024).toFixed();x5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",alreadyDownloadedKbytes:f,totalFetchedKbytes:f,totalContentKbytes:Math.floor(c.j/1024).toFixed()},
{videoId:b,gj:a.j});case 4:d6(a),g.sa(e)}})},zZa=function(a){var b=3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},AZa=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,e6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);v5(a.va,{entityKey:a.j.key,failureReason:c});d=g.kJ(a.j.key).entityId;var f={videoId:d,gj:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=oYa(k));x5(l,f);g.sa(e)})},e6=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.ta(f,2),g.A(f,BZa(a,function(k){return c?f5(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return i5(k,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Us.resolve(void 0)}),4);
if(2!=f.j)return g.ua(f,0);e=g.va(f);return e instanceof g.Ns&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.hs("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Va(0)})},BZa=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,m5(a.u,{mode:"readwrite",Lc:!0},function(e){var f=[h5(e,c,"transfer")];b&&f.push(b(e));return g.Us.all(f)}),0)})},a6=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},uZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.kJ(b.key),d=c.entityId,e=g.lJ(d,"playbackData"),g.A(l,p5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},d6=function(a){a.C.start(a.Ga||18E5)},vZa=function(a){return void 0!==f6[a.transferState]},wZa=function(a,b){var c=f6[a.transferState],d=f6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},g6=function(a,b){var c=this;
this.X=a;this.api=b;this.S=new g.Ut;this.u=new iYa(function(){return CZa(c)},function(){DZa(c)},this.api.zp(),this.api.N.bind(this.api));
this.B=new u5(this.api);this.C=new g.Qj;jYa(this.u)},CZa=function(a){return g.B(function(b){a.api.Oa("onOrchestrationBecameLeader");
a.j&&a.D||EZa(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},EZa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,s5(),2);if(3!=e.j){b=e.u;if(!b)return t5("PES is undefined"),e.return();a.j=new $5(b,a.api,a.u,a.B);c=a.iG(b);d=a;return g.A(e,SYa(b,c,a.u,a.B),3)}d.D=e.u;return g.A(e,FZa(a),0)})},FZa=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return t5("transferManager is undefined"),c.return();if(a.j.j){c.Va(2);break}return g.A(c,b6(a.j),2);case 2:return g.A(c,a.nz(),4);case 4:return a.J=g.Cr(function(){a.nz()},9E5),g.Tr(g.Vr(),function(){return a.MI()}),g.A(c,s5(),5);
case 5:return b=c.u,g.A(c,eYa(b),6);case 6:kYa(a.u),g.sa(c)}})},DZa=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Oa("onOrchestrationLostLeader");a.C=new g.Qj;g.sa(d)})},GZa=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,s5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,q5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.r(c),e=d.next();case 4:if(e.done){k.Va(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Va(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,o5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Va(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},h6=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,s5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.lJ(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},IYa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new P5(c,n,p);return Q5(n)});
l=XXa(f,k);jYa(a.u);return m.return(l)})},IZa=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.GI(),c=AXa(a),d=g.pI(HZa),g.ta(k,2),g.A(k,g.AG(b,c,d),4);case 4:e=k.u;g.ua(k,3);break;case 2:throw f=g.va(k),t5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return k.return(e.videos.map(function(l){return l.offlineVideoData}))}})},i6=function(a,b,c){this.j=a;
this.X=b;this.u=c},LZa=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=F5(b),d=g.kJ(b.entityKey),e=d.entityId,g.ta(m,2),g.A(m,JZa(a,e),4);case 4:g.ua(m,3);break;case 2:return f=g.va(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Ns&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=KZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},MZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=F5(b),d=g.kJ(b.entityKey),e=d.entityId,g.A(n,p5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(n,3);return g.A(n,JZa(a,e,f.addedTimestampMillis),5);case 5:k=KZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ua(n,4);break;case 3:return l=g.va(n),l instanceof Error&&"No data"===l.message?g.A(n,J5(e,a.j,b,a.u),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Ns&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},NZa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.ta(e,2),d=g.kJ(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,xYa(a.j,b,a.u),5):g.A(e,J5(d,a.j,b,a.u),5);case 5:g.ua(e,3);break;case 2:return g.va(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},JZa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,IZa([b]),2);case 2:return d=n.u,e=d[0],g.A(n,OZa(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.ta(n,4);var p=I5(k.thumbnail),q=I5(l.avatar);return g.A(n,sYa(p.concat(q)),6);case 6:g.ua(n,0);break;case 4:m=g.va(n);if(!a.X.N("woffle_disable_thumbnails"))throw m;g.sa(n)}})},OZa=function(a,b,c){var d,e,f,k,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.lJ(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.lJ(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.lJ(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.lJ(b.videoId,"playbackData"),offlineVideoPolicy:g.lJ(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.X.N("woffle_entity_migration")?(m={key:g.lJ(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.lJ(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.lJ(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,m5(a.j,{mode:"readwrite",Lc:!0},function(q){var t=h5(q,f,"ytMainChannelEntity"),v=h5(q,k,"ytMainVideoEntity"),x=h5(q,l,"ytMainDownloadedVideoEntity"),
y=h5(q,m,"mainVideoDownloadStateEntity");q=h5(q,n,"mainVideoEntity");return g.Us.all([t,v,x,y,q])}),3)):g.A(p,m5(a.j,{mode:"readwrite",
Lc:!0},function(q){var t=h5(q,f,"ytMainChannelEntity"),v=h5(q,k,"ytMainVideoEntity");q=h5(q,l,"ytMainDownloadedVideoEntity");return g.Us.all([t,v,q])}),3)}return p.return({videoEntity:k,
channelEntity:f,ria:l})})},KZa=function(a,b,c){b=g.lJ(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:PZa});return{actionType:a,entityKey:b,actionMetadata:c}},j6=function(){g6.apply(this,arguments);
this.K="ytMainDownloadedVideoEntity"},QZa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,s5(),2):(a=b.u)?g.A(b,m5(a,{mode:"readwrite",Lc:!0},function(c){var d=f5(c,"ytMainDownloadedVideoEntity"),e=f5(c,"ytMainVideoEntity"),f=f5(c,"mainVideoEntity");return g.Us.all([d,e,f]).then(function(k){k=g.r(k);var l=k.next().value,m=k.next().value,n=k.next().value;k={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.kJ(p.id).entityId;k[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.kJ(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.kJ(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(k));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=k[q],v=l[q];t={key:g.lJ(q,"mainVideoDownloadStateEntity"),playbackData:g.lJ(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.lJ(q,"mainVideoEntity"),videoId:q,title:v.title,thumbnail:v.thumbnail,localizedStrings:v.localizedStrings,lengthSeconds:v.lengthSeconds,publishedTimestampMillis:v.publishedTimestampMillis,
formattedDescription:v.formattedDescription,owner:v.channelOwner,downloadState:t.key},t];n.push(h5(c,q[0],"mainVideoEntity"),h5(c,q[1],"mainVideoDownloadStateEntity"))}return g.Us.all(n)})}),0):b.return()})},k6=function(){g.cK.apply(this,arguments)};
g.w(s4,r4);g.w(t4,s4);t4.prototype.kd=function(){return[]};
g.w(u4,s4);u4.prototype.kd=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.u(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.u(new Set(a)))};
g.w(v4,s4);v4.prototype.kd=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.u(new Set(a)))};
g.w(w4,r4);w4.prototype.kd=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.u(new Set(a)))};
g.w(x4,s4);x4.prototype.kd=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.u((new w4(c.value)).kd()));return[].concat(g.u(new Set(a)))};
g.w(y4,s4);y4.prototype.kd=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.u(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.u(new Set(a)))};
g.w(z4,s4);z4.prototype.kd=function(){return[]};
g.w(A4,s4);A4.prototype.kd=function(){return[]};
g.w(B4,s4);B4.prototype.kd=function(){return[]};
g.w(C4,s4);C4.prototype.kd=function(){return[]};
g.w(D4,s4);D4.prototype.kd=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(E4,s4);E4.prototype.kd=function(){return[]};
g.w(F4,s4);F4.prototype.kd=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.u(this.j.fakeChildren));return[].concat(g.u(new Set(a)))};
g.w(G4,s4);G4.prototype.kd=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(H4,s4);H4.prototype.kd=function(){return[]};
g.w(I4,r4);I4.prototype.kd=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.u(new Set(a)))};
g.w(J4,s4);J4.prototype.kd=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.u((new I4(this.j.userState)).kd()));return[].concat(g.u(new Set(a)))};
g.w(K4,s4);K4.prototype.kd=function(){return[]};
g.w(L4,s4);L4.prototype.kd=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.u(new Set(a)))};
g.w(M4,s4);M4.prototype.kd=function(){return[]};
g.w(N4,s4);N4.prototype.kd=function(){return[]};
g.w(O4,s4);O4.prototype.kd=function(){return[]};
g.w(P4,s4);P4.prototype.kd=function(){return[]};
g.w(Q4,s4);Q4.prototype.kd=function(){return[]};
g.w(R4,s4);R4.prototype.kd=function(){return[]};
g.w(S4,s4);S4.prototype.kd=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.u(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(T4,s4);T4.prototype.kd=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.u(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.u(this.j.captionTrack));return[].concat(g.u(new Set(a)))};
g.w(U4,s4);U4.prototype.kd=function(){return[]};
g.w(V4,s4);V4.prototype.kd=function(){return[]};
g.w(W4,s4);W4.prototype.kd=function(){return[]};
g.w(X4,s4);X4.prototype.kd=function(){return[]};
var HZa=["offline"],DYa=["offline/get_playback_data_entity"],RZa={P2:"captionTrack",A6:"ytMainDownloadedVideoEntity",B6:"ytMainVideoEntity",o$:"ytMainChannelEntity",p$:"mainVideoEntity",q$:"mainVideoDownloadStateEntity",jca:"offlineOrchestrationActionWrapperEntity",tca:"offlineVideoPolicy",uca:"offlineVideoStreams",gda:"playbackData",bea:"orchestrationWebSamplingEntity",Nfa:"transfer"};g.w(Z4,g.Is);g.w(a5,FXa);
a5.prototype.B=function(a,b){b=$4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
a5.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw BXa(1);var c=new TextDecoder;b=$4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
g.w(b5,FXa);b5.prototype.B=function(a){return a};
b5.prototype.u=function(a){if(a instanceof Uint8Array)throw BXa(0);return a};
var JXa={buttonEntity:U4,captionTrack:O4,channelHandle:t4,commerceCartListEntity:W4,downloadQualityPickerEntity:C4,fakeChannel:u4,fakePlaylist:v4,fakePlaylistEntryCollection:x4,fakeVideo:y4,fakeVideoDescription:z4,iconBadgeEntity:X4,liveChatPollStateEntity:B4,logoEntity:A4,mainPlaylistEntity:H4,mainVideoDownloadStateEntity:D4,mainVideoEntity:J4,markersVisibilityOverrideEntity:M4,offlineOrchestrationActionWrapperEntity:P4,offlineVideoPolicy:Q4,offlineVideoStreams:R4,offlineabilityEntity:E4,orchestrationWebSamplingEntity:F4,
pinnedProductEntity:N4,playbackData:S4,transfer:T4,videoPlaybackPositionEntity:V4,ytMainChannelEntity:K4,ytMainDownloadedVideoEntity:G4,ytMainVideoEntity:L4},d5;g.w(l5,g.G);l5.prototype.B=function(a){WXa(this,a.data)};
l5.prototype.qa=function(){this.channel.close()};
var r5;g.w(u5,g.G);u5.prototype.B=function(a){this.api.Oa("onOfflineOperationFailure",a.data)};
u5.prototype.C=function(a){this.api.ea("offlinetransferpause",a.data)};
u5.prototype.qa=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};fYa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};iYa.prototype.uf=function(){this.j&&w5(this)};var C5=g.C.caches,B5,D5;y5.prototype.open=function(a){return C5.open(A5(a))};
y5.prototype.has=function(a){return C5.has(A5(a))};
y5.prototype.delete=function(a){return C5.delete(A5(a))};
y5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Va(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Va(3);break;case 5:return n.return()}})};
g.w(z5,y5);z5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.Js("CacheStorage keys"),g.A(n,C5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{CC:f}:{CC:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.CC;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(RZa).map(function(a){return RZa[a]});
var wYa="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainVideoEntity mainVideoDownloadStateEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(M5,K5);M5.prototype.B=function(a){return G5(a)?BYa(this,a):H5(a)?CYa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(O5,K5);O5.prototype.B=function(a){return G5(a)?FYa(this,a):H5(a)?GYa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
O5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=F5(a),g.A(f,p5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,o5(b.j,d,"transfer"),5);case 5:e=g.kJ(d.key).entityId;x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,gj:d});g.ua(f,4);break;case 3:return g.va(f),f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var WYa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var R5;OYa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(U5,g.G);U5.prototype.qa=function(){this.K&&this.K();g.G.prototype.qa.call(this)};
U5.prototype.createAction=function(a,b){var c=g.kJ(a.entityKey).entityType,d=g.Pv(16);return new P5(c,d,a,b.actionId,b.rootActionId)};
U5.prototype.Z=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.kJ(l),n=m.entityId,QYa(b.j,n)||e.push(l);return g.A(q,YYa(b,e),2)}p=q.u;return g.A(q,W5(b,p),0)})};
U5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,ZYa(a),0)})};g.h=eZa.prototype;
g.h.nY=function(a){var b=this,c,d,e,f;return g.B(function(k){if(!g.U(a.state,128))return k.Va(0);var l=null==(c=a.state.getData())?void 0:c.errorCode,m=null==(d=a.state.getData())?void 0:d.xI,n=null==(e=a.state.getData())?void 0:e.cB;f=b.N("html5_eliminate_net_retryexhausted_error")&&"net.connect"===l&&1===n||"net.retryexhausted"===l&&(null==m?0:m.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==l?0:l.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(k,
b.hs(b.player.getVideoData().videoId,f),0)})};
g.h.hs=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(Y5(c,a,!1,!0),d.Va(0)):g.A(d,X5(c,a),3)}g.yD(a,4);return g.A(d,c.j.hs(b),0)})};
g.h.uC=function(a){2===a.status?(a.status!==this.B&&(c6(this.j),g.yD(a.videoId,2)),a.fz&&yZa(this.j,a.videoId,a.fz)):4===a.status?(X5(this,a.videoId),this.hs(a.videoId,a.JB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&xZa(this.j);this.B=a.status;this.api.Oa("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.WH=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,X5(a,b),2)}return g.A(c,a.j.WH(),0)})};
g.h.N=function(a){return this.api.V().N(a)};g.w(Z5,g.G);Z5.prototype.qa=function(){this.u&&this.u();g.G.prototype.qa.call(this)};
Z5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.kJ(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,lZa(b,e),0)})};g.w($5,g.G);g.h=$5.prototype;g.h.qa=function(){this.K&&this.K();this.S.dispose();this.C.dispose();this.ma&&g.ag(this.D.B,this.ma);this.Z&&g.ag(this.D.B,this.Z);g.G.prototype.qa.call(this)};
g.h.x_=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.lJ(a,"transfer"),b.j&&c===b.j.key?(Y5(b.J,b.B,!0),b.C.stop(),e.Va(0)):g.A(e,m5(b.u,{mode:"readwrite",Lc:!0},function(f){return e5(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",h5(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&nYa({videoId:a,gj:d});g.sa(e)})};
g.h.w_=function(){this.j&&this.B&&Y5(this.J,this.B,!1);this.C.stop()};
g.h.rz=function(){this.j?rZa(this,this.j):b6(this)};
g.h.jU=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Va(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Va(3);break}c=b;return g.A(d,p5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Va(3);break}return g.A(d,sZa(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,b6(b),0)}})};
g.h.hs=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&zZa(c)?g.A(f,e6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,AZa(c,a),3)}3!=f.j&&(d=g.kJ(c.j.key).entityId,x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,gj:c.j}));a6(c);e=b6(c,!0);b&&b(e);g.sa(f)})};
g.h.WH=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return zZa(b)?g.A(m,e6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,AZa(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.kJ(b.j.key).entityId,x5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,gj:b.j}),d=IYa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.lJ(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=Q5(new P5("playbackData",c,f)),g.A(m,o5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);a6(b);l=b6(b,!0);a&&a(l);g.sa(m)})};
var l6={},f6=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.h=g6.prototype;g.h.iG=function(a){var b={};return b.playbackData=new M5(a,this.X,this.B),b.transfer=new O5(a),b};
g.h.MI=function(){var a=this;return g.B(function(b){return a.j?g.A(b,pZa(a.j),0):b.Va(0)})};
g.h.isOrchestrationLeader=function(){return this.u.j};
g.h.lI=function(a){var b=this.B;b.api.ea("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.rz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,s5(),2);b=d.u;if(!b)return d.return();c=g.lJ(a,"transfer");return g.A(d,m5(b,{mode:"readwrite",Lc:!0},function(e){return e5(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",h5(e,f,"transfer").then(function(){x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,gj:f});return g.Us.resolve(null)})):
g.Us.resolve(null)})}),0)})};
g.h.nz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.S.tf()?g.A(p,s5(),2):p.return(GZa());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,q5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.r(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.kJ(m.key).entityId,f.push(n));return f.length?p.return(h6(b,f,b.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return h6(this,["!*$_ALL_ENTITIES_!*$"],this.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(i6,K5);i6.prototype.B=function(a){return G5(a)?LZa(this,a):H5(a)?MZa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&a.entityKey?NZa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var PZa=[10];g.w(j6,g6);j6.prototype.iG=function(a){var b=g6.prototype.iG.call(this,a);b.ytMainDownloadedVideoEntity=new i6(a,this.X,this.B);return b};
j6.prototype.MI=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,g6.prototype.MI.call(a),2):a.X.N("woffle_entity_migration")?g.A(b,QZa(),0):b.Va(0)})};g.w(k6,g.cK);g.h=k6.prototype;g.h.create=function(){var a=this.player.V();g.RC(a)&&(this.j=new j6(a,this.player))};
g.h.bj=function(){return!1};
g.h.yI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(h6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.nz=function(a){return this.j.nz(a)};
g.h.lI=function(a){this.j.lI(a)};
g.h.rz=function(a){return this.j.rz(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.bK("offline",k6);})(_yt_player);
